import { Home, Car, User, Briefcase, GraduationCap, Coins, Building2 } from "lucide-react"

export const loanTypes = [
  {
    id: "home-loan",
    icon: Home,
    title: "Home Loan",
    description: "Make your dream home a reality with our affordable home loan solutions.",
    rate: "8.5% p.a.",
    maxAmount: "Up to ₹5 Cr",
    tenure: "Up to 30 years",
    features: [
      "Competitive interest rates",
      "Quick approval process",
      "Flexible repayment options",
      "No hidden charges",
      "Balance transfer facility",
    ],
    color: "bg-blue-500/10 text-blue-600 border-blue-500/20",
  },
  {
    id: "car-loan",
    icon: Car,
    title: "Car Loan",
    description: "Drive your dream car today with our hassle-free car loan options.",
    rate: "9.0% p.a.",
    maxAmount: "Up to ₹1 Cr",
    tenure: "Up to 7 years",
    features: [
      "100% on-road funding",
      "Minimal documentation",
      "Same day approval",
      "Attractive interest rates",
      "Used car loans available",
    ],
    color: "bg-emerald-500/10 text-emerald-600 border-emerald-500/20",
  },
  {
    id: "personal-loan",
    icon: User,
    title: "Personal Loan",
    description: "Get instant personal loans for weddings, travel, medical emergencies, or any personal need.",
    rate: "10.5% p.a.",
    maxAmount: "Up to ₹40 L",
    tenure: "Up to 5 years",
    features: [
      "No collateral required",
      "Instant approval",
      "Minimal documentation",
      "Flexible tenure options",
      "Quick disbursal",
    ],
    color: "bg-violet-500/10 text-violet-600 border-violet-500/20",
  },
  {
    id: "business-loan",
    icon: Briefcase,
    title: "Business Loan",
    description: "Fuel your business growth with our working capital and expansion loans.",
    rate: "11.0% p.a.",
    maxAmount: "Up to ₹50 L",
    tenure: "Up to 5 years",
    features: [
      "Collateral-free options",
      "Quick processing",
      "Flexible repayment",
      "Working capital loans",
      "Equipment financing",
    ],
    color: "bg-amber-500/10 text-amber-600 border-amber-500/20",
  },
  {
    id: "education-loan",
    icon: GraduationCap,
    title: "Education Loan",
    description: "Invest in your future with education loans for studies in India and abroad.",
    rate: "8.0% p.a.",
    maxAmount: "Up to ₹1.5 Cr",
    tenure: "Up to 15 years",
    features: [
      "Cover tuition & living expenses",
      "Moratorium period available",
      "Tax benefits under 80E",
      "No margin for loans up to ₹4L",
      "Study abroad options",
    ],
    color: "bg-rose-500/10 text-rose-600 border-rose-500/20",
  },
  {
    id: "gold-loan",
    icon: Coins,
    title: "Gold Loan",
    description: "Get quick funds against your gold jewelry with minimal documentation.",
    rate: "7.5% p.a.",
    maxAmount: "Up to ₹2 Cr",
    tenure: "Up to 3 years",
    features: [
      "Instant disbursal",
      "Minimal documentation",
      "Safe gold storage",
      "Flexible repayment",
      "No processing fee",
    ],
    color: "bg-yellow-500/10 text-yellow-600 border-yellow-500/20",
  },
  {
    id: "lap",
    icon: Building2,
    title: "Loan Against Property",
    description: "Unlock the value of your property with attractive interest rates.",
    rate: "9.5% p.a.",
    maxAmount: "Up to ₹10 Cr",
    tenure: "Up to 20 years",
    features: [
      "High loan amount",
      "Lower interest rates",
      "Long repayment tenure",
      "Property remains with you",
      "Flexible end-use",
    ],
    color: "bg-cyan-500/10 text-cyan-600 border-cyan-500/20",
  },
]